services:
  d-browser-use:
    build:
      context: ./python
      dockerfile: Dockerfile
    image: d-browser-use
    ports:
      - "8000:8000"
    shm_size: "2gb"
    working_dir: /app
    volumes:
      - ./python:/app
    environment:
      - PYTHONUNBUFFERED=1

  redis:
    image: redis
    ports:
      - "6379:6379"
