# https://github.com/vercel/storage/issues/281

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  serverless-redis-http:
    ports:
      - "8079:80"
    image: hiett/serverless-redis-http:latest
    environment:
      SRH_MODE: env
      SRH_TOKEN: token
      SRH_CONNECTION_STRING: "redis://redis:6379"
